function B = GetB_(i)
  switch i
    case 1
      B = @(x) (1-abs(x)).*(abs(x) <= 1) + ...
            0        .*(abs(x) > 1)
    case 2
      B = @(x) 1 ./2 .*( ...
        (2-(abs(x)-0.5).^2 - (abs(x)+0.5).^2).*(abs(x) <= 0.5) + ...
        ((abs(x) - 1.5).^2)                  .*(0.5 < abs(x)).*(abs(x) <= 1.5) + ...
        0                                    .*(abs(x) > 1.5) ...
      )
    case 3
      B = @(x) 1/6 .* (...
        ((2-abs(x)).^3 - 4 .*(1-abs(x)).^3).*(abs(x) <= 1) +...
        (2-abs(x)).^3                      .*(1 < abs(x)).*(abs(x) <= 2) +...
        0                                  .*(abs(x)<2)...
      )
  endswitch
endfunction